### ISSUE TITLE
Why you change symlink() method interface?

### ISSUE THREAD

**Issue by maxgu** [Falc/FlysystemLocalSymlinkPlugin#3]
http://php.net/manual/en/function.symlink.php
```php
bool symlink ( string $target , string $link )
```
in your solution
```php
public function handle($symlink, $target)
{
    return symlink($target, $symlink);
}
```
Why you change method interface? `$target`expected as first argument.

**Comment by Falc** [comment]
I've changed from `symlink($symlink, $target)` to `symlink($target, $symlink)` to match PHP's `symlink()` and retagged as v1.0.0.
